<%@ Page Title="" Language="C#" MasterPageFile="~/IoT/MasterIoT.master" AutoEventWireup="true" CodeFile="Insights.aspx.cs" Inherits="IoT_Insights" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
	<br />
<h2 style="box-sizing: border-box; outline: none !important; font-family: TedNext, Helvetica, sans-serif; font-weight: 600; line-height: 1.1; color: rgb(65, 64, 66); margin: 0px; font-size: 30px; padding: 0px 0px 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Expand revenue opportunities</h2>
<p style="box-sizing: border-box; outline: none !important; margin: 0px 0px 10px; font-size: 14px; font-weight: 400; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
	Across the customer lifecycle and new markets, IoT helps organizations address new income streams with value-added services. Intelligently connecting devices can also allow for energy- and resource-efficient processes that help create more value with fewer resources. Take full advantage of a platform built for innovation to drive growth.</p>
<h2 style="box-sizing: border-box; outline: none !important; font-family: TedNext, Helvetica, sans-serif; font-weight: 600; line-height: 1.1; color: rgb(65, 64, 66); margin: 0px; font-size: 3rem; padding: 30px 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
	<br class="Apple-interchange-newline" />
	Deploy comprehensive IoT solutions</h2>
<h3 style="box-sizing: border-box; outline: none !important; font-family: TedNext, Helvetica, sans-serif; font-weight: 600; line-height: 1.1; color: rgb(0, 174, 199); margin: 0px; font-size: 22px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Asset monitoring and management</h3>
<p style="box-sizing: border-box; outline: none !important; margin: 10px 0px; font-size: 14px; font-weight: 400; display: block; line-height: 20px; padding: 0px; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
	Maintain visibility and control over your vital corporate assets to make more informed, real-time decisions. Whether you need to monitor a fleet of trucks, building infrastructure, or factory machinery, our solutions can help you improve the efficiency of your company’s investments and catch issues before they grow into costly problems.</p>
<br style="box-sizing: border-box; outline: none !important; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
<h3 style="box-sizing: border-box; outline: none !important; font-family: TedNext, Helvetica, sans-serif; font-weight: 600; line-height: 1.1; color: rgb(0, 174, 199); margin: 0px; font-size: 22px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Safety and security</h3>
<p style="box-sizing: border-box; outline: none !important; margin: 10px 0px; font-size: 14px; font-weight: 400; display: block; line-height: 20px; padding: 0px; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
	Protect people and property alike with our suite of safety and security solutions. Our automated, fully integrated systems deliver peace of mind by simplifying how you monitor and reduce hazards in nearly any location, from retail branches and restricted areas to public buildings and underground garages.</p>
<br style="box-sizing: border-box; outline: none !important; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
<h3 style="box-sizing: border-box; outline: none !important; font-family: TedNext, Helvetica, sans-serif; font-weight: 600; line-height: 1.1; color: rgb(0, 174, 199); margin: 0px; font-size: 22px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Customer engagement</h3>
<p style="box-sizing: border-box; outline: none !important; margin: 10px 0px; font-size: 14px; font-weight: 400; display: block; line-height: 20px; padding: 0px; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
	Customers increasingly seek interactive and personalized digital encounters. Connect with customers through enriched experiences powered by IoT. Our solutions can help deepen product engagement, or leverage technologies such as digital signage for a more dynamic, vibrant retail space.</p>
<p style="box-sizing: border-box; outline: none !important; margin: 0px 0px 10px; font-size: 14px; font-weight: 400; color: rgb(65, 64, 66); font-family: TedNext, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
	&nbsp;</p>
<br />

</asp:Content>

